name: CI Docs ii002713

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz cmake g++ make

      - name: Configure project
        working-directory: trunk/ii002713/task_03/src
        run: cmake -B build -S .
      - name: Build project
        working-directory: trunk/ii002713/task_03/src
        run: cmake --build build
      - name: Run tests
        working-directory: trunk/ii002713/task_03/src/build
        run: ctest --output-on-failure
      - name: Generate Doxygen documentation
        working-directory: trunk/ii002713/task_03/src
        run: cmake --build build --target doc
      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7d2c1b4cc6df8eab6789b1c77dbbdbcd6a2b  # pinned SHA (v3.9.3)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: trunk/ii002713/task_03/doc/html
